### ISSUE TITLE
Error while reading D3plot file

### ISSUE THREAD

**Issue by StefanVR46** [qd-cae/Codie-D3plot#3]
Hi,

I get the following error message:
` d3plot = D3plot(filepath,use_femzip=False,read_states=None)
RuntimeError: Wrong filetype 1041203856 != 1 in header of d3plot`

For writing the d3plot file we use the default settings.  
I'm using Python 2.7.12 , Windows 7 Professional 64 Bit and LS-Dyna Version R 7.1.2

Greetings
Stefan

**Comment by qd-codie** [comment]
The first thing the library checks is the filetype flag (it's at word position 11). If this fails, there are not many possibilities what's wrong:
(1) Your file is double precision (the library can not read double precision)
(2) There might be a problem with the machines endianess vs the files endianness

In case (1) you can simply tell LS-Dyna to output the file in single-precision despite calculating in double precision. No one usually cares about those digits anyways for numeric reasons. Never understood why they do it as default.

In case (2) I might need to take a look at the binary file myself.

Any matches? I've written the library with the newest database guide from LSTC. So it should be able to handle R 7.1.2, .... if everything is documented appropriately.

**Comment by StefanVR46** [comment]
Unfortunately i already had:
``*DATABASE_FORMAT
$$   IFORM   IBINARY
         0         1``

in my code. I don't have one D3plot file as output i got serveral, maybe this might change something?

Thank you anyway

**Comment by qd-codie** [comment]
Is it still the same error message?

Multiple files should be no problem, it should handle this. The library searches for the additional files. Despite that, the additional files only contain the state information. A mistake there would definitely lead to other errors. 

If it's ok for you I can take a glimpse at the file myself. I'm sure I can work this one out fast myself. Can't be that huge of an issue.
constantin.diez@gmail.com

**Comment by StefanVR46** [comment]
You got mail (maybe check your junk mail?).

**Comment by qd-codie** [comment]
**Bug Description:**
I've figured it out. The problem is related to filenames. The library searches all subfiles with name: "d3plot*". On windows side there seems to be a bug in the search function, so that it also considers your script file "D3plot_Reader.py". It should not happen, since the first letter is different and secondly the state files only have numbers appended. 

**User Fix**
Just _rename your script_ to a more different name or _move the results in a subfolder_.

**Developer Fix**
I will fix this issue this week, should be done quite fast. I will add the letter sensitivity, as well as the number filtering. It should not happen again after that with your current script's name.

**Comment by StefanVR46** [comment]
Worked for me too. Many thanks!!

**Comment by qd-codie** [comment]
I've implemented a first fix (filename is now case sensitive). Did not know, that windows is not case sensitive. The fix is implemented in the [qd library](https://github.com/qd-cae/qd), which is the predecessor of this one. Still need to fix the number extensions only though.
